### PR TITLE
Added Purple As A New Color

### PR DESCRIPTION
**Pull request by Deadmano**
Added a custom purple style. The themes lacked a true deep purple color, so I've quickly added one in based on my previous edits for Air legacy... Tested and working without any issues. Optionally can be called "darkpurple" as it is darker than actual purple (of which there are many variations).

### CODE REVIEW

**Comment by Elundris** [comment]
Merged and made a few tiny tweaks for consistency. Cheers!

**Comment by sebie** [comment]
It is in the latest release! :tada:

**Comment by commit-sudoku** [comment]
for true material colours the exact values would be 

	colors {
		Focus="103 58 183 255"		//dark purple main color
		Focus2="126 87 194 255"		//lighter purple for headers
		Focus3="126 87 194 150"		//lighter purple with opacity for content boxes
		Focus4="94 53 177 255"		//darker purple for contrast
	}

**Comment by Elundris** [comment]
Since this was contributed by Deadmano, I'll let him make the call. I think they both look fine personally.

**Comment by Deadmano** [comment]
Thanks for your response, Kanna! I had no idea what "material color" 
was, to be honest... So I did a bit of searching and was pleasantly 
surprised by Google's design guidelines and so I decided to follow in 
its massive footsteps and re-do my color scheme from scratch. I have 
created a pull request and am pleased by the results. The colors blend 
in well and the contrast is there. Too bad we can't specify actual 
text/text hover colors as that could help with text being a bit dark 
when hovered upon in some places (may just be my monitor).

Elundris thanks once again for creating an amazing Skin and allowing us 
the ability to edit their color schemes to fit in with our tastes! :)
------------------------------------------------------------------------
*Phillip Stolić
Deadmano Inc. :: Director*
/IT Specialist - Repairs, Upgrades, Sales/
------------------------------------------------------------------------
*Mobile:* +27 73 709 4595
*Email:* info@deadmano.com <mailto:info@deadmano.com>
*Website:* http://www.deadmano.com

**Pull request merged**
