### PR TITLE
Changed avatar borders

### PR DESCRIPTION
**Pull request by 1112e**
Removed the white circle as well as a few tweaks. Looks better with dark theme

### CODE REVIEW

**Comment by sebie** [comment]
The status circles, I would call them look nice. Maybe a bit thinner?

**Comment by 1112e** [comment]
Thats as thin as it can go, otherwise the corners of the avatars stick out

**Comment by 1112e** [comment]
O wait i just realised what the white part on the original was for. It was the same color as the background. I'll fix this to match dark mode

**Comment by 1112e** [comment]
Actually this way works with both light and dark, where with the ring there would have to be 2 files to switch.

**Comment by 1112e** [comment]
turned out was i was trying to do was already done

**Pull request closed without merging**
