### PR TITLE
Slight variation on existing color themes

### PR DESCRIPTION
**Pull request by dafzor**
gunmetalbreeze
It's just gunmetal color scheme with breeze's Focus2 color on text for improved readability.

### CODE REVIEW

**Comment by sebie** [comment]
Thank you for the contribution @dafzor ! :trophy: 

I don't know how to say this. As it is a modification of an existing scheme, but with a different focus does it count as a new theme? Up to @Elundris ultimately. However @djwetbeatz do you have anything to comment?

Other then that; would you mind taking a screenshot of the scheme in action and embeding it into your reply? It would be highly appriciated.

**Comment by dafzor** [comment]
Updated the original post with a screenshot.

And yes it's definitely not an original theme, just a slight variation on the gunmetal one since imo the text color had too little contrast to be readable.

I personally use it so figured I'd contribute it here, if you feel it's best left out of the main distribution i'll just keep my local copy :)

**Comment by djwetbeatz** [comment]
I think it's fine as a contribution, I suppose. It does improve readability and doesn't look half bad. Though I don't know if it merits its own theme necessarily, since it's a combination of two preexisting ones, and it's relatively easy to swap a few values if you want to mix and match some color schemes.

But it also wouldn't be a problem really since it doesn't change anything that's already there, just adds a new style file. So no harm done, I guess. We'll see what @Elundris has to say.

**Comment by Elundris** [comment]
I actually think this is a brilliant idea for the gunmetal theme by default. It's problematic since gunmetal is all greyscale, so having a touch of color on the text elements helps. I updated the develop branch to have gunmetal use the sky focus colors for the text only (personal preference, I think it pops a bit nicer than breeze).

Let me know what you guys think!

**Comment by dafzor** [comment]
Tried both and honestly the difference is too small for me to notice (could be my monitors just suck) so I guess I'd be fine with both.

**Comment by Elundris** [comment]
Closing since this has been implemented on the develop branch. Will roll out when Steam's beta goes live.

**Pull request closed without merging**
