### PR TITLE
Icon changes

### PR DESCRIPTION
**Pull request by 1112e**

### CODE REVIEW

**Comment by sebie** [comment]
That looks cool! And thank you @1112e for all the contributions to Air; I sure do notice that you are submitting issues and PR's nearly everyday; which is crazy awesome?!

Keep up the good work. :+1:

**Comment by djwetbeatz** [comment]
I think this would be a nice addition to the +Extras folder. I'm sure a lot of people might like both of these as available options. Good contribution! :+1:

**Comment by Elundris** [comment]
I've been sticking with the Material Design icons for most of Air, so I won't be making these changes in the official build. Thanks though!

For reference: https://www.google.com/design/icons/

**Comment by djwetbeatz** [comment]
@Elundris, I obviously respect any decisions of yours to include or exclude certain things in the official air build, however I just wanted to note that both of the icons that @1112e has shown are actually part of the icons you linked. They're under "Content" and "Social" and the icon names are "Mail/Mark Unread" and "Mood". So I think they do still fit within the guidelines. Though if you still would rather not include them as an extra or something, then I respect that.

**Comment by 1112e** [comment]
Yup, got these straight from there

**Comment by Elundris** [comment]
*cough cough*

Heh, well, that's embarrassing. :/

My main concern about adding lots of extras is the need to upkeep them when stuff changes. I had a bit of "option creep" with Classic and it got quite annoying to manage towards the end. That's why I was much more hesitant to add tons of stuff to the new Air. So in that vein, I don't want to add them into the official build, though I'm not sure if there's a way to surface unofficial tweaks in some way? Any thoughts?

**Comment by 1112e** [comment]
I was trying to make my own fork with tweaks like this, but i had a hard time keeping it synced with your branch as GitHub isn't really made for that.

**Pull request closed without merging**
