### PR TITLE
Added Hover Visual Feedback (inbox_button)

### PR DESCRIPTION
**Pull request by Win7yes**
I don't know if anyone has requested this before or anything, but I thought I'd do it anyway.
It's just a minor change, and only changes one small aspect that personally bothered me.
It's fine if you decide not to merge this, after all, it's just a small personal change.

Changes:
* Added visual feedback for mouse hovering on the Notification Button (`inbox_button/inbox_button_active`).  

* Adds changes to `Resource\layout\steamrootdialog.layout`.

* Changes to `Graphics\onfocus\active_circle.tga` to make it look darker.

* And adds `Graphics\onfocus\hover_circle.tga`.

### CODE REVIEW

**Comment by sebie** [comment]
Thanks for the PR @Win7yes .

Would you mind taking a screenshot of it, in action and embeding it into your reply? It would be highly appriciated :trophy:. Also if this does not get merged, an alternative might be that it gets put up into the Wiki, if anyone else wants to change it as you did.

Oh, and I touched up on you comment, feel free to edit it; I just expanded it so it was clear what you changed and your reasoning behind it.

Thanks again!

**Comment by Win7yes** [comment]
Sure, here it is
air skin hover thingy
Just that basic thing, to show when you hover over it

**Comment by sebie** [comment]
It fits in with Google's material design, so a +1 from me. 

Opinions or Comments @Elundris , @djwetbeatz ?

**Comment by djwetbeatz** [comment]
I think this would look great. It's not a terribly dramatic change, but it adds a nice little bit of visual feedback, so I don't see much harm in it.

**Comment by sebie** [comment]
Only down side I see (which just came to me) was that it may have to apply to all buttons, right?

**Comment by Win7yes** [comment]
Well the effect right now just applies to that button because it seemed kind of visual feedback lacking, but for example the menu button (the 3 horizontal lines) has the white when hover and clicking.

**Comment by sebie** [comment]
It's good that you can see that as well. Other then that, I would say you're gold.

**Comment by Elundris** [comment]
The "active circles" as I've been calling them are really only used by Material Design as an on-click reaction. A good example is in the Google Play Music desktop site or Google's Inbox.

A lot of MD doesn't have crazy hover effects, though this is probably due to the fact that it's mostly designed for touch interfaces. I'm still debating on how to best handle hover effects consistently in Air...

**Pull request closed without merging**
